CREATE TABLE usuario (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  email  VARCHAR2(150) NOT NULL,
  telefono VARCHAR2(20) NOT NULL,
  CONSTRAINT uq_usuario_email UNIQUE(email)
);

-- 2. Productos
CREATE TABLE producto (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  stock  NUMBER NOT NULL,
  precio NUMBER(10,2) NOT NULL,
  CONSTRAINT uq_producto_nombre UNIQUE(nombre)
);

-- 3. Carritos
CREATE TABLE carrito (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id NUMBER NOT NULL,
  cantidad    NUMBER      NOT NULL,
  CONSTRAINT fk_carrito_producto
    FOREIGN KEY (producto_id)
    REFERENCES producto(id)
);

COMMIT;